name = "IEEE14"
authors = ["Andreas Heuermann"]

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
NaiveONNX = "135c1d4d-7f3e-476b-9774-5f1a5fa3495d"
NonLinearSystemNeuralNetworkFMU = "cef0780c-fc83-4b94-9c0c-d964a51a3c65"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
DrWatson = "2.12.7"
NaiveONNX = "0.2.0"
NonLinearSystemNeuralNetworkFMU = "0.5.2"
julia = "1.9.0"
