name = "ScalableTranslationStatistics"
authors = ["Andreas Heuermann"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
NaiveONNX = "135c1d4d-7f3e-476b-9774-5f1a5fa3495d"
NonLinearSystemNeuralNetworkFMU = "cef0780c-fc83-4b94-9c0c-d964a51a3c65"

[compat]
DrWatson = "2.12.1"
NaiveONNX = "0.1.0"
NonLinearSystemNeuralNetworkFMU = "0.3.0"
julia = "1.8.1"
