name: Linux Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7.3']
        julia-arch: [x64]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            ort_url: 'https://github.com/microsoft/onnxruntime/releases/download/v1.12.1/onnxruntime-linux-x64-1.12.1.tgz'
            ort_archieve_name: 'onnxruntime-linux-x64-1.12.1.tgz'
            ort_dir: 'onnxruntime-linux-x64-1.12.1'
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      # Build onnxWrapper library
      - name: Download ONNX Runtime
        run: |
          wget -q ${{ matrix.ort_url }}
          tar -xf ${{ matrix.ort_archieve_name }}
          rm ${{ matrix.ort_archieve_name }}

      # Setup OpenModelica for OMJulia.jl
      - uses: AnHeuermann/setup-openmodelica@main
        with:
          version: 'stable'

      # Build and test NonLinearSystemNeuralNetworkFMU.jl
      - uses: julia-actions/setup-julia@v1
        env:
          ORT_DIR: ${{ort_dir}}
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
