name: Base tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7.3']
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            ort_url: 'https://github.com/microsoft/onnxruntime/releases/download/v1.12.1/onnxruntime-linux-x64-1.12.1.tgz'
            ort_archieve_name: 'onnxruntime-linux-x64-1.12.1.tgz'
            ort_dir: 'onnxruntime-linux-x64-1.12.1'
          - os: windows-latest
            ort_url: 'https://github.com/microsoft/onnxruntime/releases/download/v1.12.1/onnxruntime-win-x64-1.12.1.zip'
            ort_archieve_name: 'onnxruntime-win-x64-1.12.1.zip'
            ort_dir: 'onnxruntime-win-x64-1.12.1'
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Download ONNX Runtime
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            wget -q ${{ matrix.ort_url }}
            tar -xf ${{ matrix.ort_archieve_name }}
            rm ${{ matrix.ort_archieve_name }}
          elif [ "$RUNNER_OS" == "Windows" ]; then
            C:\\msys64\\usr\\bin\\wget.exe -q ${{ matrix.ort_url }}
            7zip x ${{ matrix.ort_archieve_name }}
            rm ${{ matrix.ort_archieve_name }}
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash

      - name: Configure CMake
        run: cmake -S src/onnxWrapper/ -B src/onnxWrapper/build/ -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DORT_DIR=${{ github.workspace }}/${{ matrix.ort_dir }}

      - name: Build C Sources
        run: cmake --build src/onnxWrapper/build --config ${{ env.BUILD_TYPE }} --target install

      - uses: AnHeuermann/setup-openmodelica@main
        with:
          version: 'stable'

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
