name: Documentation

on:
  push:
    branches: main
    tags: '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      # Setup OpenModelica for OMJulia.jl
      - uses: AnHeuermann/setup-openmodelica@main
        with:
          version: 'stable'

      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7.3'
      # Workaround for issue #30
      # TODO: Revert
      - name: Install dependencies, build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
        run: julia -e 'using Pkg; Pkg.add(name="Documenter", version="0.27"); Pkg.activate(pwd()); include("docs/make.jl")'
      # TODO: Remove when switching back to HTML doc
      - uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ${{ github.workspace }}/docs/build/NonLinearSystemNeuralNetworkFMU.jl.pdf
